spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//127.0.0.1:3306/tiku
    username: root
    password: 1234
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: search-mysql
  profiles:
    active: dev
server:
  port: 8081