spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my-books
    username: root
    password: 1234
  cloud:
    nacos:
      server-addr: 192.168.10.99:8848
  application:
    name: search-mysql
  profiles:
    active: dev
server:
  port: 8081
logging:
  level:
    com.search_mysql.mapper: debug
