server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.10.99:8848
    gateway:
      routes:
        - id: search-mysql
          uri: lb://search-mysql
          predicates:
            - Path=/search-mysql/**
